apiVersion: v1
kind: Service
metadata:
  name: go-weather-service
spec:
  selector:
    app: go-weather
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-weather-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-weather
  template:
    metadata:
      labels:
        app: go-weather
    spec:
      containers:
        - name: go-weather
          image: devcenter14/goweather:v2
          ports:
            - containerPort: 8080
